import "./cache-interaction";
import "./timer/timer";
import "./timer/display-timer";
import "./menu/pause-component";
import "./world/tree";
import "./world/rock";
import "./world/bush";
import "./world/campfire";
import "./world/log";
